--@block
CREATE DATABASE 'notesdb';

--@block 
DROP TABLE IF EXISTS `Notes`;
CREATE TABLE `Notes` (
  `S.N` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Title` VARCHAR(255),
  `Description` TEXT,
  `Timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;



